### ISSUE TITLE
error:MODULE -gunner script-could not be loaded 

### ISSUE THREAD

**Issue by dromian** [xVinnie/gunner-script#3]
module.exports = function gunner(dispatch){
^^^^^^

SyntaxError: Missing initializer in const declaration
    at Module._compile (internal/modules/cjs/loader.js:749:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at ModuleManager.load (C:\Users\Gabriel\Desktop\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleManager.js:148:43)
    at installedModules.forEach.mod (C:\Users\Gabriel\Desktop\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleManager.js:57:22)
    at Map.forEach (<anonymous>)

that is the error

**Comment by xxwix** [comment]
i'm having the same issue, i'm using Caali's proxy
